### ISSUE TITLE
Issues with Raag, Source, and Search

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/KhajanaAPI#4]
From @ManjotS:

tried to find vah vah gobind singh, didnt come up in search results

but some results show undefined and no raag
http://dev.sikhitothemax.org/search.php?q=vvgs&type=1&source=all

**Comment by ManjotS** [comment]
This was fixed with db dump from igurbani 2 and sttm 3 + manual work
