### ISSUE TITLE
Clone of GurbaniNow API

### ISSUE THREAD

**Issue by Sarabveer** [KhalisFoundation/KhajanaAPI#6]
Kick me off, then copy me? Nice 👎 

#### Khajana

![Khajana](https://puu.sh/tAiqb/eed31a5707.png)

#### GurbaniNow
![GurbaniNow](https://puu.sh/tAiuY/ef16bc67a8.png)

**Comment by navdeepsinghkhalsa** [comment]
@Sarabveer The work that you put into the Khajana API is much appreciated, brother, but closer inspection after your departure and thinking ahead to our future needs led to a need to think about best practices when serving data via an API and much rewriting. That there are similarities in the two and other Gurbani APIs is a validation that we're all on the right track and it's a shame that we couldn't continue working together. We hope you can join again to prevent duplication of effort and collaborate on an offering. It's also validating for us to see our ideas replicated in your project(s). All the best to you, Singh Jee! Akaal Sahaai
